# Generated by Selenium IDE
import pandas
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestExcelreader():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    self.excel_data_df = pandas.read_excel("C:\\Users\\yogesh.tala\\Downloads\\excel.xlsx", sheet_name='my')
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_excelreader(self):
    #self.driver.find_element(By.CSS_SELECTOR, ".isUndragged .quantumWizButtonPaperbuttonLabel").click()
    #self.driver.find_element(By.ID, "identifierId").click()
    #self.driver.find_element(By.ID, "identifierId").send_keys("ytala1986@gmail.com")
    #self.driver.find_element(By.ID, "identifierId").send_keys(Keys.ENTER)
    #self.driver.find_element(By.NAME, "password").send_keys("xxxx")
    #self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    for i in range(4):
      self.driver.get("https://docs.google.com/forms/d/e/1FAIpQLSeyporZ30nzujz0kyLyDFQNd1ybNisBz4A9r9PpCoRjlgCWcw/viewform?vc=0&c=0&w=1&flr=0&gxids=7628")
      self.driver.set_window_size(1041, 680)
      self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewNumberedItemContainer:nth-child(1) .quantumWizTextinputPaperinputInput").click()
      self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewNumberedItemContainer:nth-child(1) .quantumWizTextinputPaperinputInput").click()
      value = self.excel_data_df.values[i, 0]
      self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewNumberedItemContainer:nth-child(1) .quantumWizTextinputPaperinputInput").send_keys(value)
      value = self.excel_data_df.values[i, 1]
      self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewNumberedItemContainer:nth-child(2) .quantumWizTextinputPaperinputInput").send_keys(value)
      self.driver.find_element(By.CSS_SELECTOR, ".quantumWizTextinputPapertextareaInput").click()
      value = self.excel_data_df.values[i,2]
      self.driver.find_element(By.CSS_SELECTOR, ".quantumWizTextinputPapertextareaInput").send_keys(value)
      self.driver.find_element(By.CSS_SELECTOR, ".appsMaterialWizButtonPaperbuttonLabel").click()
  
